// <auto-generated />
using System;
using Fablab.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fablab.Models.Migrations
{
    [DbContext(typeof(FablabDBContext))]
    [Migration("20191120201534_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fablab.Models.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("Cad_software");

                    b.Property<string>("Email");

                    b.Property<string>("Facebook");

                    b.Property<string>("Gender");

                    b.Property<string>("Group");

                    b.Property<string>("Interest");

                    b.Property<string>("Invoice_disabled");

                    b.Property<string>("Job");

                    b.Property<string>("Last_name");

                    b.Property<string>("Name");

                    b.Property<string>("Newsletter");

                    b.Property<string>("Phone");

                    b.Property<string>("Projects");

                    b.Property<string>("Signature");

                    b.Property<string>("Tags");

                    b.Property<string>("Twitter");

                    b.Property<string>("Validated_training");

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Fablab.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<int>("Invoice");

                    b.Property<int>("Month");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Fablab.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Roles");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
